spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ReactJsSbMysqlApp
    username: root
    password: sekhar
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

camel:
  component:
    servlet:
      mapping:
        contextPath= /api/*

  springboot:
    main-run-controller:true